# -*- coding: utf-8 -*-
"""PrintMessage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqndvJy5jsvJDMkcRrgd5UtkUw-bG4x3
"""

print("Hello World")